[development]
TEST = 1
MONGO_DB_HOST = "localhost"
MONGO_DB_PORT = 27019
MONGO_DB_USER = "root"
MONGO_DB_PASSWORD = "root"

[testing]
TEST = 0
MONGO_DB_HOST = "mongo"
MONGO_DB_PORT = 27017
MONGO_DB_USER = "root"
MONGO_DB_PASSWORD = "root"
